exec:
  allow:
    - '^dart-sass-embedded$'
    - '^go$'
    - '^npx$'
    - '^postcss$'
    - '^rst2html.py$'
    - '^rst2html$'
    - '^asciidoctor$'
  osEnv: 
    - (?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|HOME|GEM_PATH)$